export const PRODUCTS = [
  {
    id: "1",
    name: "Logitech G502 LightSpeed",
    description:
      "Souris gamer, Capteur optique, Sans-fil, Pour droitier, 16 000 dpi, 11 bouton",
    price: "500",
    category: "souris",
    image: require("../assets/images/products/s1.jpg"),
  },
  {
    id: "2",
    name: "Razer DeathAdder V2 X HyperSpeed",
    description:
      "Souris gamer, Capteur optique, Sans fil, Pour droitier, 14000 dpi, 7 boutons",
    price: "260",
    category: "souris",
    image: require("../assets/images/products/s2.jpg"),
  },
  {
    id: "3",
    name: "Corsair Harpoon Wireless RGB",
    description:
      "Souris gamer, Capteur optique, Sans fil, Pour droitier, 1000 dpi, 6 boutons",
    price: "300",
    category: "souris",
    image: require("../assets/images/products/s3.jpg"),
  },
  {
    id: "4",
    name: "Logitech G203 LightSync-Noir",
    description:
      "Souris gamer, Capteur optique, Filiaire, Pour droitier, 8000 dpi, 8 boutons",
    price: "280",
    category: "souris",
    image: require("../assets/images/products/s4.jpg"),
  },
  {
    id: "5",
    name: "Logitech G402 Hyperion Fury FPS",
    description:
      "Souris gamer, Capteur optique, Filiaire, Pour droitier, 4000 dpi, 8 boutons",
    price: "280",
    category: "souris",
    image: require("../assets/images/products/s5.jpg"),
  },
  {
    id: "6",
    name: "Asus ROG Gladius III",
    description:
      "Souris gamer, Capteur optique, filiaire, Pour droitier, 19000 dpi, 6 boutons",
    price: "580",
    category: "souris",
    image: require("../assets/images/products/s6.jpg"),
  },
  {
    id: "7",
    name: "StreetSeries Rival 5 - Noir",
    description:
      "Souris gamer, Capteur optique, filiaire, Pour droitier, 18000 dpi, 9 boutons",
    price: "400",
    category: "souris",
    image: require("../assets/images/products/s7.jpg"),
  },
  {
    id: "8",
    name: "Razer DeathAdder Essential 2021-Blanc ",
    description:
      "Souris gamer, Capteur optique, filiaire, Pour droitier, 18000 dpi, 9 boutons",
    price: "360",
    category: "souris",
    image: require("../assets/images/products/s8.jpg"),
  },
  {
    id: "9",
    name: "Corsair M65 RGB ULTRA",
    description:
      "Souris gamer, Capteur optique, filiaire, Pour droitier, 26000 dpi, 8 boutons",
    price: "370",
    category: "souris",
    image: require("../assets/images/products/s9.jpg"),
  },
  {
    id: "10",
    name: "Asus TUF M4 Wireless",
    description:
      "Souris gamer, Capteur optique, Sans-fil, Pour droitier, 12000 dpi, 6 boutons",
    price: "500",
    category: "souris",
    image: require("../assets/images/products/s10.jpg"),
  },
  {
    id: "11",
    name: "Logitech G213 Prodigy",
    description:
      "Clavier gamer, Classique, Filiaire, Classique (membrane), 16, 8 millions de couleurs",
    price: "590",
    category: "claviers",
    image: require("../assets/images/products/c1.jpg"),
  },
  {
    id: "12",
    name: "Corsair K55 RGB Pro",
    description:
      "Clavier gamer, Classique, Filiaire, Classique (membrane), 16, 8 millions de couleurs",
    price: "490",
    category: "claviers",
    image: require("../assets/images/products/c2.jpg"),
  },
  {
    id: "13",
    name: "Asus TUF K3",
    description:
      "Clavier gamer, Classique, Filiaire, Classique (membrane), 16, 8 millions de couleurs",
    price: "890",
    category: "claviers",
    image: require("../assets/images/products/c3.jpg"),
  },
  {
    id: "14",
    name: "Corsair K70 RGB Pro - Cherry MX Red",
    description:
      "Clavier gamer, Classique, Filiaire, Classique , Mécanique (switchs), Cherry MX Red, 16, 8 millions de couleurs",
    price: "2500",
    category: "claviers",
    image: require("../assets/images/products/c4.jpg"),
  },
  {
    id: "15",
    name: "Asus ROG Scope TKL - Moonlight",
    description:
      "Clavier gamer, TKL, Filiaire, Mécanique (switchs), Asus ROG NX Red, 16, 8 millions de couleurs",
    price: "1390",
    category: "claviers",
    image: require("../assets/images/products/c5.jpg"),
  },
  {
    id: "16",
    name: "Asus TUF K1",
    description:
      "Clavier gamer, Classique, Filiaire (membrane), 16,8 millions de couleurs",
    price: "590",
    category: "claviers",
    image: require("../assets/images/products/c6.jpg"),
  },
  {
    id: "17",
    name: "Logitech G915 Lightspeed - GL Tactile",
    description:
      "Clavier gamer, Classique, Sans-fil, Mécanique(Switchs),GL Tactile, 16,8 millions de couleurs",
    price: "2490",
    category: "claviers",
    image: require("../assets/images/products/c7.jpg"),
  },
  {
    id: "18",
    name: "Logitech G413 TKL SE- KaiHua Brown",
    description:
      "Clavier gamer, TKL, Filiaire, Mécanique(Switchs),Kaihua Brown, 16,8 millions de couleurs",
    price: "640",
    category: "claviers",
    image: require("../assets/images/products/c8.jpg"),
  },
  {
    id: "19",
    name: "Ironclad V3-NOIR-Red Blood",
    description:
      "Clavier gamer, TKL, Filiaire, Mécanique(Switchs),Red Blood, Rétro-éclairage RGB",
    price: "1490",
    category: "claviers",
    image: require("../assets/images/products/c9.jpg"),
  },
  {
    id: "20",
    name: "Razer Cynosa Lite",
    description:
      "Clavier gamer, Classique, Filiaire, 16,8 millions De couleurs",
    price: "400",
    category: "claviers",
    image: require("../assets/images/products/c10.jpg"),
  },
  {
    id: "21",
    name: "JBL Quantom 400",
    description:
      "Casque Gamer, 7.1 Surround, Circum-aural (englobe les oreilles), Néodyme de 50 mm, 1x 3,5 mm ou 1x USB",
    price: "790",
    category: "casques",
    image: require("../assets/images/products/ca1.jpg"),
  },
  {
    id: "22",
    name: "SteelSeries Arctis Pro Wireless - Noir",
    description:
      "Casque Gamer, 7.1 Surround, Circum-aural (englobe les oreilles), Néodyme de 50 mm, 1x 3,5 mm ou 1x USB",
    price: "1990",
    category: "casques",
    image: require("../assets/images/products/ca2.jpg"),
  },
  {
    id: "23",
    name: "JBL Quantum 200",
    description:
      "Casque Gamer, 7.1 Surround, Circum-aural (englobe les oreilles), Néodyme de 50 mm, 1x 3,5 mm ou 1x USB",
    price: "440",
    category: "casques",
    image: require("../assets/images/products/ca3.jpg"),
  },
  {
    id: "24",
    name: "Logitech G Pro X - Noir",
    description:
      "Casque Gamer, 7.1 Surround, Circum-aural (englobe les oreilles), Néodyme de 50 mm, 1x 3,5 mm ou 1x USB",
    price: "1190",
    category: "casques",
    image: require("../assets/images/products/ca4.jpg"),
  },
  {
    id: "25",
    name: "SteelSeries Arctis 1Wireless - Noir",
    description:
      "Casque Gamer, 7.1 Surround, Circum-aural (englobe les oreilles), Néodyme de 40 mm, 1x 3,5 mm ou 1x USB",
    price: "740",
    category: "casques",
    image: require("../assets/images/products/ca5.jpg"),
  },
  {
    id: "26",
    name: "Corsair Void RGB Elite",
    description:
      "Casque Gamer, 7.1 Surround, Circum-aural (englobe les oreilles), Néodyme de 50 mm, 1x 3,5 mm ou 1x USB",
    price: "1190",
    category: "casques",
    image: require("../assets/images/products/ca6.jpg"),
  },
  {
    id: "27",
    name: "JNL Quantum 100 - Noir",
    description:
      "Casque Gamer, 7.1 Surround, Circum-aural (englobe les oreilles), Néodyme de 40 mm, 1x 3,5 mm ",
    price: "390",
    category: "casques",
    image: require("../assets/images/products/ca7.jpg"),
  },
  {
    id: "28",
    name: "Corsair HS55 Stereo - Noir",
    description:
      "Casque Gamer, 7.1 Surround, Circum-aural (englobe les oreilles), Néodyme de 40 mm, 1x 3,5 mm ",
    price: "690",
    category: "casques",
    image: require("../assets/images/products/ca8.jpg"),
  },
  {
    id: "29",
    name: "JNL Quantum 100 - Bleu",
    description:
      "Casque Gamer, 7.1 Surround, Circum-aural (englobe les oreilles), Néodyme de 40 mm, 1x 3,5 mm ",
    price: "390",
    category: "casques",
    image: require("../assets/images/products/ca9.jpg"),
  },
  {
    id: "30",
    name: "Logitech G435 Lightspeed - Noir",
    description:
      "Casque Gamer, 7.1 Surround, Circum-aural (englobe les oreilles), Néodyme de 40 mm, 1x 3,5 mm 2,4Ghz sur USB ou Bluetooth",
    price: "790",
    category: "casques",
    image: require("../assets/images/products/ca10.jpg"),
  },
  {
    id: "31",
    name: "Sony Dualsense - blanc",
    description: "Manette sans-fil, Compatible PC, PS5, Android, IOS",
    price: "790",
    category: "manettes",
    image: require("../assets/images/products/m1.jpg"),
  },
  {
    id: "32",
    name: "Microsoft Xbox Series X + Câble USB-C 2,75m",
    description:
      "Manette sans-fil, Compatible PC, Xbox One, Xbox Series, Android, iOs",
    price: "690",
    category: "manettes",
    image: require("../assets/images/products/m2.jpg"),
  },
  {
    id: "33",
    name: "MSI Force GC30 V2 - Noir",
    description: "Manette sans-fil, Compatible PC, Android",
    price: "540",
    category: "manettes",
    image: require("../assets/images/products/m3.jpg"),
  },
  {
    id: "34",
    name: "Microsoft Xbox Wireless Controller - Gold Shadow",
    description:
      "Manette sans-fil, Compatible PC, Xbox One, Xbox Series, Android, iOs",
    price: "690",
    category: "manettes",
    image: require("../assets/images/products/m4.jpg"),
  },
  {
    id: "35",
    name: "Manette filaire PC",
    description: "Manette filaire, Compatible PC uniquement",
    price: "220",
    category: "manettes",
    image: require("../assets/images/products/m5.jpg"),
  },
  {
    id: "36",
    name: "Microsoft Xbox Wireless Controller Series 2 - Noir",
    description:
      "Manette sans-fil, Compatible PC, Xbox One, Xbox Series, Android, iOs",
    price: "1900",
    category: "manettes",
    image: require("../assets/images/products/m6.jpg"),
  },
  {
    id: "37",
    name: "MSI Force GC30 V2 - Noir",
    description: "Manette sans-fil, Compatible PC, Android",
    price: "540",
    category: "manettes",
    image: require("../assets/images/products/m7.jpg"),
  },
  {
    id: "38",
    name: "Razer Wolverine V2 Chroma - Noir",
    description: "Manette sans-fil, Compatible PC, Xbox One, Xbox Series",
    price: "1590",
    category: "manettes",
    image: require("../assets/images/products/m8.jpg"),
  },
  {
    id: "39",
    name: "Sony Dualsense - Purple",
    description: "Manette sans-fil, Compatible PC, PS5, Android, IOS",
    price: "790",
    category: "manettes",
    image: require("../assets/images/products/m9.jpg"),
  },
  {
    id: "40",
    name: "The G-Lab K-Pad Thorium Switch",
    description: "Manette sans-fil, Compatible PC, Nintendo Switch",
    price: "30",
    category: "manettes",
    image: require("../assets/images/products/m10.jpg"),
  },
  {
    id: "41",
    name: "Asus ROG STRIX B760-F GAMING WI-FI",
    description:
      "Intel B760, Socket LGA1700, ATX, WI-FI 6e génération, compatible Intel Core 12 et 13e génération",
    price: "26900",
    category: "carte_meres",
    image: require("../assets/images/products/cm1.jpg"),
  },
  {
    id: "42",
    name: "Gigabyte B760 Gaming x DDR4",
    description:
      "Intel B760, Socket LGA1700, ATX, WI-FI 6e génération, compatible Intel Core 12 et 13e génération, support DDR4",
    price: "15400",
    category: "carte_meres",
    image: require("../assets/images/products/cm2.jpg"),
  },
  {
    id: "43",
    name: "Asus TUF GAMING B760-PLUS WI-FI",
    description:
      "Intel B760, Socket LGA1700, ATX, WI-FI 6e génération, compatible Intel Core 12 et 13e génération, support DDR5",
    price: "24500",
    category: "carte_meres",
    image: require("../assets/images/products/cm3.jpg"),
  },
  {
    id: "44",
    name: "Asus PRIME B760-PLUS",
    description:
      "Intel B760, Socket LGA1700, ATX, WI-FI 6e génération, compatible Intel Core 12 et 13e génération, Support DDR5",
    price: "16400",
    category: "carte_meres",
    image: require("../assets/images/products/cm4.jpg"),
  },
  {
    id: "45",
    name: "Asus TUF GAMING B550-PLUS",
    description:
      "Intel B760, Socket LGA1700, ATX, compatible Intel Core 12 et 13e génération",
    price: "14900",
    category: "carte_meres",
    image: require("../assets/images/products/cm5.jpg"),
  },
  {
    id: "46",
    name: "Asus PRIME B760M-PLUS",
    description:
      "Intel B760, Socket LGA1700, ATX, WI-FI 6e génération, compatible Intel Core 12,13 et 14e génération",
    price: "17800",
    category: "carte_meres",
    image: require("../assets/images/products/cm6.jpg"),
  },
  {
    id: "47",
    name: "Asus TUF GAMING B760M-PLUS II",
    description:
      "Intel B760, Socket LGA1700, ATX, compatible Intel Core 13 et 14e génération, support DDR5",
    price: "29000",
    category: "carte_meres",
    image: require("../assets/images/products/cm7.jpg"),
  },
  {
    id: "48",
    name: "Asus TUF GAMING B760M-PLUS WI-FI II",
    description:
      "Intel B760, Socket LGA1700, ATX, WI-FI 6e génération, compatible Intel Core 13 et 14e génération, support DDR5",
    price: "29000",
    category: "carte_meres",
    image: require("../assets/images/products/cm8.jpg"),
  },
  {
    id: "49",
    name: "Asus TUF GAMING Z790-BTF WI-FI",
    description:
      "Intel Z790, Socket LGA1700, ATX, WI-FI 7e génération, compatible Intel Core 13 et 14e génération, support DDR5",
    price: "29000",
    category: "carte_meres",
    image: require("../assets/images/products/cm9.jpg"),
  },
  {
    id: "50",
    name: "Asus PRIME A520M-R",
    description:
      "AMD A520, Socket AM4, Micro-ATX, Compatible processeur AMD Ryzen 3000/5000",
    price: "18000",
    category: "carte_meres",
    image: require("../assets/images/products/cm10.jpg"),
  },
  {
    id: "51",
    name: "AMD Ryzen 7 7800 X 3D (4.2 GHz)",
    description:
      "Processeur 8 coeurs, 4.40GHz, 96 Mo, AMD Zen 4, TDP 120 Watts, Socket AM5, Version boîte sans ventilateur",
    price: "45490",
    category: "processeurs",
    image: require("../assets/images/products/proc1.jpg"),
  },
  {
    id: "52",
    name: "Intel Core i7 12700KF",
    description:
      "12 coeurs, 20 threads, 3.6 GHz, 25 Mo, Alder Lake, 190 Watts, BX8171512700KF",
    price: "37000",
    category: "processeurs",
    image: require("../assets/images/products/proc2.jpg"),
  },
  {
    id: "53",
    name: "AMD Ryzen 7 5800X",
    description:
      "Processeur 8 coeurs, 4.40GHz, 96 Mo, AMD Zen 4, TDP 120 Watts, Socket AM5, Version boîte sans ventilateur",
    price: "25000",
    category: "processeurs",
    image: require("../assets/images/products/proc3.jpg"),
  },
  {
    id: "54",
    name: "Intel Core i5 12400",
    description:
      "6 coeurs, 12threads, 2.5 GHz, 18Mo, Alder Lake, 65/117Watts, BX8071512400KF",
    price: "19900",
    category: "processeurs",
    image: require("../assets/images/products/proc4.jpg"),
  },
  {
    id: "55",
    name: "Intel Core i5 13600KF",
    description:
      "14 coeurs, 20 threads, 3.5 GHz, 25 Mo, Raptor Lake, BX8171512700KF",
    price: "36800",
    category: "processeurs",
    image: require("../assets/images/products/proc5.jpg"),
  },
  {
    id: "56",
    name: "AMD Ryzen 5 3600",
    description: "6 coeurs, 3.6 GHz, 32 Mo, AMD Ryzen, 65 Watts",
    price: "13000",
    category: "processeurs",
    image: require("../assets/images/products/proc6.jpg"),
  },
  {
    id: "57",
    name: "AMD Ryzen 5 5600X",
    description:
      "Processeur 6 coeurs, 3.70GHz, 96 Mo, AMD Zen 4, TDP 65 Watts, Socket AM5, Version boîte sans ventilateur",
    price: "23000",
    category: "processeurs",
    image: require("../assets/images/products/proc7.jpg"),
  },
  {
    id: "58",
    name: "AMD Ryzen 7 5800X",
    description:
      "Processeur 8 coeurs, 4.40GHz, 96 Mo, AMD Zen 4, TDP 120 Watts, Socket AM5, Version boîte sans ventilateur",
    price: "23600",
    category: "processeurs",
    image: require("../assets/images/products/proc8.jpg"),
  },
  {
    id: "59",
    name: "Intel Core i5 10400F",
    description:
      "6 coeurs, 12 threads, 2.9 GHz, 12 Mo, Comet Lake, BX8171512700KF",
    price: "15200",
    category: "processeurs",
    image: require("../assets/images/products/proc9.jpg"),
  },
  {
    id: "60",
    name: "AMD Ryzen 9 5900X",
    description:
      'Processeur 6 coeurs, ".70GHz, 96 Mo, AMD Zen 4, TDP 65 Watts, Socket AM5, Version boîte sans ventilateur',
    price: "36900",
    category: "processeurs",
    image: require("../assets/images/products/proc10.jpg"),
  },
  {
    id: "61",
    name: "Gigabyte GeForce RTX 4060 WINDFORCE OC",
    description: "GeForece RTX 4060, PCI-Express 4.0 8x, 8 Go GDDR6, DLSS 3",
    price: "36900",
    category: "carte_graphiques",
    image: require("../assets/images/products/graph1.jpg"),
  },
  {
    id: "62",
    name: "Gigabyte GeForce RTX 4070 WINDFORCE OC",
    description: "GeForece RTX 4060, PCI-Express 4.0 16x, 12 Go GDDR6, DLSS 3",
    price: "66500",
    category: "carte_graphiques",
    image: require("../assets/images/products/graph2.jpg"),
  },
  {
    id: "63",
    name: "Gigabyte Radeon RX 6600 EAGLE",
    description: "Radeon RX 6600, PCI-Express 4.0 8x, 8 Go GDDR6",
    price: "23500",
    category: "carte_graphiques",
    image: require("../assets/images/products/graph3.jpg"),
  },
  {
    id: "64",
    name: "Gigabyte GeForce RTX 3070 GAMING OC V2B (LHR)",
    description:
      "GeForece RTX 3060, PCI-Express 4.0 16x, 12 Go GDDR6, LHR, DLSS 3",
    price: "35690",
    category: "carte_graphiques",
    image: require("../assets/images/products/graph4.jpg"),
  },
  {
    id: "65",
    name: "MSI GeForece RTX 4060 VENTUS 2x VLACK 8G OC",
    description: "GeForece RTX 4060, PCI-Express 4.0 8x, 8 Go GDDR6, DLSS 3",
    price: "34590",
    category: "carte_graphiques",
    image: require("../assets/images/products/graph5.jpg"),
  },
  {
    id: "66",
    name: "MSI GeForece RTX 3060 VENTUS 2x VLACK 8G OC",
    description: "GeForece RTX 3060, PCI-Express 4.0 8x, 8 Go GDDR6",
    price: "32400",
    category: "carte_graphiques",
    image: require("../assets/images/products/graph6.jpg"),
  },
  {
    id: "67",
    name: "MSI GeForece GT 1030 LP OC-2Go (DDR4)",
    description: "GeForece GT 1030, PCI-Express 16x, 2 Go",
    price: "10000",
    category: "carte_graphiques",
    image: require("../assets/images/products/graph7.jpg"),
  },
  {
    id: "68",
    name: "ASRock Radeon RX 6600 Challenger D",
    description: "Radeon RX 6600, PCI-Express 4.0, 8 Go GDDR6",
    price: "24000",
    category: "carte_graphiques",
    image: require("../assets/images/products/graph8.jpg"),
  },
  {
    id: "69",
    name: "Asus GeForce RTX 4070 DUAL OC",
    description: "GeForce RTX 4070, PCI-Express 4.0 16x, 12 Go GDDR6X, DLSS 3",
    price: "30000",
    category: "carte_graphiques",
    image: require("../assets/images/products/graph9.jpg"),
  },
  {
    id: "70",
    name: "Gigabyte GeForce RTX 4070 WINDFORCE OC",
    description: "GeForece RTX 4060, PCI-Express 4.0 8x, 8 Go GDDR6, DLSS 3",
    price: "66500",
    category: "carte_graphiques",
    image: require("../assets/images/products/graph10.jpg"),
  },
  {
    id: "71",
    name: "Samsung 980 Pro - 1To",
    description: "SSD 1To, PCO Express 4.0 4x, M2 NVME",
    price: "11200",
    category: "ssds",
    image: require("../assets/images/products/ssd1.jpg"),
  },
  {
    id: "72",
    name: "Crucial P3 1To",
    description: "SSD 1To, PCO Express 4.0 4x, M2 NVME",
    price: "9900",
    category: "ssds",
    image: require("../assets/images/products/ssd2.jpg"),
  },
  {
    id: "73",
    name: "Kingston NV2-1To",
    description: "SSD 1To, PCO Express 4.0 4x, M2 NVME",
    price: "10000",
    category: "ssds",
    image: require("../assets/images/products/ssd3.jpg"),
  },
  {
    id: "74",
    name: "Samsung 970 EVO Plus- 2To",
    description: "SSD 2To, PCO Express 3.0 4x, M2 NVME",
    price: "16000",
    category: "ssds",
    image: require("../assets/images/products/ssd4.jpg"),
  },
  {
    id: "75",
    name: "Samsung 990 PRO - 2To",
    description: "SSD 2To, PCO Express 4.0 4x, M2 NVME",
    price: "15000",
    category: "ssds",
    image: require("../assets/images/products/ssd5.jpg"),
  },
  {
    id: "76",
    name: "Corsair MP600 Pro NH - 8To",
    description: "SSD 8To, PCO Express 4.0 4x, M2 NVME",
    price: "40000",
    category: "ssds",
    image: require("../assets/images/products/ssd6.jpg"),
  },
  {
    id: "77",
    name: "Corsair MP600 Pro NH- 4To",
    description: "SSD 4To, PCO Express 4.0 4x, M2 NVME",
    price: "2000",
    category: "ssds",
    image: require("../assets/images/products/ssd7.jpg"),
  },
  {
    id: "78",
    name: "Fox Spirit PM70 PRO - 1920 Go",
    description: "SSD 1920 Go, PCO Express 4.0 4x, M2 NVME",
    price: "1400",
    category: "ssds",
    image: require("../assets/images/products/ssd8.jpg"),
  },
  {
    id: "79",
    name: "Fox Spirit PM70 PRO - 960Go",
    description: "SSD 960Go, PCO Express 4.0 4x, M2 NVME",
    price: "120",
    category: "ssds",
    image: require("../assets/images/products/ssd9.jpg"),
  },
  {
    id: "80",
    name: "Textorm BM40 - 1920Go",
    description: "SSD 1920 Go, PCO Express 4.0 4x, M2 NVME",
    price: "1980",
    category: "ssds",
    image: require("../assets/images/products/ssd10.jpg"),
  },
  {
    id: "81",
    name: "Corsair Vengeance LPX Black DDR4 2x16Go 3200 MHz ",
    description: "RAM PC, DDR4, 32Go, 3200MHz - PC25600",
    price: "10000",
    category: "rams",
    image: require("../assets/images/products/ram1.jpg"),
  },
  {
    id: "82",
    name: "Corsair Vengeance LPX Black DDR5 2x16Go 6000 MHz ",
    description: "RAM PC, DDR5, 32Go, 6000MHz - PC48000",
    price: "18000",
    category: "rams",
    image: require("../assets/images/products/ram2.jpg"),
  },
  {
    id: "83",
    name: "Corsair Vengeance LPX Black DDR4 2x8Go 3200 MHz ",
    description: "RAM PC, DDR4, 32Go, 3200MHz - PC25600",
    price: "8900",
    category: "rams",
    image: require("../assets/images/products/ram3.jpg"),
  },
  {
    id: "84",
    name: "Corsair Vengeance LPX Black DDR4 2x8Go 3200 MHz ",
    description: "RAM PC, DDR4, 32Go, 3200MHz - PC25600",
    price: "7800",
    category: "rams",
    image: require("../assets/images/products/ram4.jpg"),
  },
  {
    id: "85",
    name: "G.SKILL Aegis DDR3 2x8Go 1600 MHz CAS 11",
    description: "RAM PC, DDR3, 16Go, 1600MHz - PC12800",
    price: "5000",
    category: "rams",
    image: require("../assets/images/products/ram5.jpg"),
  },
  {
    id: "86",
    name: "G.SKILL Trident Z5 RGB White - 2 x 24 Go (48 Go)-DDR5 7600",
    description: "Kit RAM DDR5, 48Go, 7600 MHz, PC60800, RGB Blanc",
    price: "40000",
    category: "rams",
    image: require("../assets/images/products/ram6.jpg"),
  },
  {
    id: "87",
    name: "G.SKILL Trident Z5 RGB Blanc- 2 x 24 Go (48 Go)-DDR5 7600",
    description: "Kit RAM DDR5, 48Go, 7600 MHz, PC60800, RGB Noir",
    price: "41000",
    category: "rams",
    image: require("../assets/images/products/ram7.jpg"),
  },
  {
    id: "88",
    name: "G.SKILL Aegis DDR4 2x8Go 3200 MHz CAS 16",
    description: "RAM PC, DDR4, 16Go, 3200MHz - PC25600",
    price: "5600",
    category: "rams",
    image: require("../assets/images/products/ram8.jpg"),
  },
  {
    id: "89",
    name: "G.SKILL Extrem3 RipJaws X DDR3 2x4Go 1600 MHz CAS 9",
    description: "RAM PC, DDR3, 8Go, 1600MHz - PC12800",
    price: "4200",
    category: "rams",
    image: require("../assets/images/products/ram9.jpg"),
  },
  {
    id: "90",
    name: "G.SKILL Aegis X DDR4 2x8Go 3200 MHz CAS 16",
    description: "RAM PC, DDR4, 16Go, 3200MHz - PC12800",
    price: "5600",
    category: "rams",
    image: require("../assets/images/products/ram10.jpg"),
  },
];
export type PRODUCTTYPE = (typeof PRODUCTS)[number];
export const getRandomProducts = (slice: number): PRODUCTTYPE[] => {
  if (slice <= 0) {
    return PRODUCTS.sort(() => 0.5 - Math.random()).slice(0, 4);
  }
  return PRODUCTS.sort(() => 0.5 - Math.random()).slice(0, slice);
};
export const RANDOMPRODUCTS = PRODUCTS.sort(() => 0.5 - Math.random()).slice(
  0,
  4
);
